# Generated by Django 2.2.11 on 2020-03-21 13:25

from django.conf import settings
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supermarkets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('time_range', django.contrib.postgres.fields.ranges.DateTimeRangeField(help_text='The time range during which this slot is active', verbose_name='time range')),
                ('booked_by', models.ManyToManyField(help_text='The people that booked this time slot', to=settings.AUTH_USER_MODEL, verbose_name='booked by')),
                ('supermarket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarkets.Supermarket', verbose_name='supermarket')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
