# Generated by Django 2.2.11 on 2020-03-21 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'verbose_name': 'slot', 'verbose_name_plural': 'slots'},
        ),
    ]
