# Generated by Django 2.2.11 on 2020-03-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0002_auto_20200321_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='end_time',
            field=models.DateTimeField(help_text='The time at which this slot starts', null=True, verbose_name='end time'),
        ),
        migrations.AddField(
            model_name='slot',
            name='start_time',
            field=models.DateTimeField(help_text='The time at which this slot starts', null=True, verbose_name='start time'),
        ),
    ]
