# Generated by Django 2.2.11 on 2020-03-22 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermarkets', '0003_auto_20200321_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='district'),
        ),
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='state'),
        ),
        migrations.AddField(
            model_name='address',
            name='suburb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='suburb'),
        ),
        migrations.AddField(
            model_name='supermarket',
            name='email_address',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='fax number'),
        ),
        migrations.AddField(
            model_name='supermarket',
            name='fax_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='fax number'),
        ),
        migrations.AddField(
            model_name='supermarket',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='supermarket',
            name='proprietor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='proprietor'),
        ),
        migrations.AddField(
            model_name='supermarket',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='website'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=10, verbose_name='postal code'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=255, verbose_name='street'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_number',
            field=models.CharField(max_length=10, verbose_name='street number'),
        ),
        migrations.AlterField(
            model_name='address',
            name='town',
            field=models.CharField(max_length=255, verbose_name='town'),
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='chain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarkets.SupermarketChain', verbose_name='chain'),
        ),
    ]
